mabe02/lanterna

README.md

I thought it would be a nice idea to copy project description & wiki from googlecode to github as well. For now I stared with README since its fast and simple. Notice that screenshot is still referencing googlecode, since I'm not sure how to host it properly for a github.

README for github

---

src/main/java/com/googlecode/lanterna/terminal/ansi/CygwinTerminal.java
src/main/java/com/googlecode/lanterna/terminal/ansi/UnixTerminal.java
src/main/java/com/googlecode/lanterna/terminal/ansi/UnixishTerminal.java

This is my first throw at untangling CygwinTerminal from UnixTerminal.
It is based on Issue #139 which shows, that CygwinTerminal inherits more
from its base-class than it can handle.
I don't have cygwin anywhere near hand, so I'd appreciate someone with
cygwin to try it and report on it.
PS: I did run some of the terminal test-programs for UnixTerminal, and they looked fine to me under Linux.

Refactor UnixTerminal and CygwinTerminal.

---

src/main/java/com/googlecode/lanterna/graphics/BasicTextImage.java
src/main/java/com/googlecode/lanterna/gui2/AbstractListBox.java
src/main/java/com/googlecode/lanterna/gui2/CheckBoxList.java
src/main/java/com/googlecode/lanterna/gui2/GridLayout.java
src/main/java/com/googlecode/lanterna/gui2/RadioBoxList.java
src/main/java/com/googlecode/lanterna/screen/AbstractScreen.java
src/main/java/com/googlecode/lanterna/screen/ScreenBuffer.java
src/main/java/com/googlecode/lanterna/terminal/IOSafeExtendedTerminal.java
src/main/java/com/googlecode/lanterna/terminal/IOSafeTerminalAdapter.java
src/main/java/com/googlecode/lanterna/terminal/ansi/TelnetTerminalServer.java
src/test/java/com/googlecode/lanterna/gui2/ListBoxTest.java

When debugging a TextGui program, it is most useful to be able to watch the Screen's backbuffer as it is drawn to, rather than only after a refresh.  This commit adds a toString() to BasicTextImage and ScreenBuffer, but also to AbstractScreen(which passes it on to its backbuffer).
So far these classes all had their default toString, which made examination of contents rather hard.
This toString() is still rather simple, as it ignores attributes, CJK and colours, but enough to still help.
The result is a bit odd for VirtualScreen, as its backbuffer contains some, but not all the visible stuff. I haven't yet found out, why that is so.

TextImage.toString, ListBox, IOSafeExtendedTerminal

---

src/main/java/com/googlecode/lanterna/gui2/LinearLayout.java

I was trying to implement a toolbar similar to what nano does (see screenshot) and to do that wanted to use panels with horizontal linear layout filled on a panel. However I noticed that I'm unable to assign layout data to the action I was trying to put at the end of panel. This change fixes visibility of Alignment.

Let users be able to use LinearLayout.Alignment

---

src/main/java/com/googlecode/lanterna/gui2/AbstractBasePane.java

In any Component I used getTextGUI was returning null.
This looks like because getTextGUI merely delegates to the parent,
but AbstractBasePane.ContentHolder parent always null, since
it is a root of hierarchy. This makes this root Component return
meaningful TextGUI instance.

Fix of getTextGUI always returning null

---

src/main/java/com/googlecode/lanterna/gui2/AbstractBasePane.java
src/main/java/com/googlecode/lanterna/gui2/InteractableLookupMap.java
src/main/java/com/googlecode/lanterna/terminal/ansi/UnixLikeTerminal.java

In case of Ctrl-C or System.exit() or uncaught exception, real terminals should be completely reset: not just the stty-stuff, but also exit the private mode (which restores the visible cursor,...)
This is in response to issue #150 .

fixes for issues #150 and #164

---

src/test/java/com/googlecode/lanterna/issue/Issue150.java

This covers point 2 from Issue #150 
App behaviour is equally awful with both SwingTerminal and UnixTerminal

Issue150 demo of unexpected app failure

---

src/main/java/com/googlecode/lanterna/input/InputDecoder.java
src/test/java/com/googlecode/lanterna/terminal/TerminalInputTest.java

+ merged my previous preview (8f2d09542015ca5eb26e154eccea2ad2e1d56a91) with all the latest changes on mabe02/lanterna
+ added configurable timeout (with default of 0)
+ added option to TerminalInputTest to allow testing (with rather long 10s timeout that allows to manually type escape sequences)
+ fixed ClassCastException in TerminalInputTest, when running with Swing (where mouse reporting and timeout settings don't apply yet)
I think this now solves issue #172

reworked scanning of input bytes into KeyStrokes. (+timeout, +test)

---

src/main/java/com/googlecode/lanterna/input/DefaultKeyDecodingProfile.java
src/main/java/com/googlecode/lanterna/input/EscapeSequenceCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/KeyStroke.java

This is a first step towards supporting shifted cursor keys, function keys, home,end,pgup,pgdn.
Shift-flag is specifically **not** supported for character KeyStrokes. E.g.: "Shift-6" is '^' for English keyboards and '&' for German ones. Shift-Tab is still possible, but should be mapped to ReverseTab.
Next step will be a new CharacterPattern implementing class, that will replace  most of the individual BasicCharacterPatterns in the DefaultKeyDecodingProfile, and will support any combination of alt,ctrl,shift for some special keys, while avoiding to specify all 8 variants for each of them.

Add shiftDown support to KeyStroke

---

src/main/java/com/googlecode/lanterna/input/AltAndCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/BasicCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/CharacterPattern.java
src/main/java/com/googlecode/lanterna/input/CtrlAltAndCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/CtrlAndCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/EscapeSequenceCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/InputDecoder.java
src/main/java/com/googlecode/lanterna/input/MouseCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/NormalCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/ScreenInfoAction.java
src/main/java/com/googlecode/lanterna/input/ScreenInfoCharacterPattern.java
src/main/java/com/googlecode/lanterna/terminal/ansi/StreamBasedTerminal.java

I think I've finished it now.
This is what Lanterna would look like with a CharacterPattern as I'd have preferred.
As by-products of this change:
* cursor position reporting (and thus terminal size query) is somewhat cleaner now
* some new control- and alt-key combinations are now supported (e.g.: Alt-#, Ctrl-\\ ).
* got rid of regex-matching in Pattern classes
* ScreenInfoCharacterPattern now uses EscapeSequenceCharacterPattern for the hard work

CharacterPattern change

---

src/main/java/com/googlecode/lanterna/bundle/BundleLocator.java
src/main/java/com/googlecode/lanterna/bundle/LocalizedUiBundle.java
src/main/java/com/googlecode/lanterna/gui2/LocalizedString.java
src/main/java/com/googlecode/lanterna/gui2/dialogs/ActionListDialog.java
src/main/java/com/googlecode/lanterna/gui2/dialogs/FileDialog.java
src/main/java/com/googlecode/lanterna/gui2/dialogs/FileDialogBuilder.java
src/main/java/com/googlecode/lanterna/gui2/dialogs/ListSelectDialog.java
src/main/java/com/googlecode/lanterna/gui2/dialogs/MessageDialogButton.java
src/main/java/com/googlecode/lanterna/gui2/dialogs/TextInputDialog.java
src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java
src/main/resources/multilang/lanterna-ui.properties
src/main/resources/multilang/lanterna-ui_de.properties
src/main/resources/multilang/lanterna-ui_fr.properties

This PR is the result of the discussion on https://github.com/mabe02/lanterna/pull/191.
I'm sorry to propose it after one week and more while the refactoring was already done...
As the proposal of my first PR, the mechanism uses the built-in one provided by Java. But this time, it is more simple and righter.
For now, only the button labels are taken into account and there are two handled languages:
- the default one, English(lanterna-ui.properties)
- the French one (lanterna-ui_fr.properties)
To get another handled language, the linked lanterna-UI_XX.properties file must be added.
For example, to handle German language, lanterna-ui_de.properties must be created.
I have read your post-scriptum about https://transifex.com, and I think that it is a good way to get translations, but I'm not …

Localization proposal for short labels (OK, Yes, No, etc.)

---

src/main/java/com/googlecode/lanterna/gui2/AbstractWindow.java
src/main/java/com/googlecode/lanterna/gui2/Window.java

An even quicker fix would be to just initialize `visible` to `true` (in AbstarctWindow.java)
This PR does that, and also adds a setter `setVisible(boolean)` to Window.
An even more elaborate fix might leave initial visible at false, but set it to true when a Window is added to a TextGui. It makes a subtle difference, depending on what was the original motivation behind adding that flag.

Quickfix to make Windows visible again.

---

src/main/java/com/googlecode/lanterna/screen/TerminalScreen.java

I'd like to be able to avoid flushing of the input buffer on exit.  This PR might just be a start - next step would be getting rid of the Bufferedreader in InputDecoder.

argument to stopScreen to control flushing of input

---

src/main/java/com/googlecode/lanterna/TerminalTextUtils.java
src/test/java/com/googlecode/lanterna/TerminalTextUtilsTest.java

Ok, this is the final list of bugs identified and fixed for issue #210:
- Never break at char position 0: always leave at least one char before a line break (to prevent infinite loop)
- Also allow to break immediately after a CJK character
- Where no nice word-wrap is possible break by available space. (Just in case we eventually get non-breaking double-width chars, later.)
- Fix StringIndexOutOfBoundsException
- cut off trailing white-space after line break, rather than putting an empty string in a new line.

Fix bugs mentioned in Issue#210 and comments

---

src/main/java/com/googlecode/lanterna/gui2/dialogs/FileDialog.java

Hi,
I get a NullPointerException when the directory is null :  selecting the parent from a root directory NPE and application is locked
( on Windows I would excpect the dirve's list ... I didn't had a try on other OS ... maybe no parent for root directory ?? )
With this quick and dirty fix : no more NPE but the fileDialog becomes empty. 
No Idea how to retrieve the Drive list just for windows.
Thomas Labbé

FileDialog : NullPointerException when directory is null

---

src/main/java/com/googlecode/lanterna/gui2/dialogs/FileDialog.java

When filesystem root is reached other available roots are shown ( on windows other roots are the drives )

FileDialog.java : adding other file System roots available

---

src/main/java/com/googlecode/lanterna/gui2/table/DefaultTableRenderer.java

Calling onAdded ensures that the scrollbar has its parent set. Without
it, scrollbar’s default renderer will revert to the default theme.

Fixed scrollbar theming

---

src/main/java/com/googlecode/lanterna/screen/AbstractScreen.java

I noticed that CJKScreenTest no longer showed any double-width characters.
The problem was CJK-padding at multiple layers:  At the bottom (BasicImage) it made sure that the character was padded, and that any double-width character immediately to the left of current position was removed.
Then, further up the call stack, AbstractScreen also tried to pad CJK, which meant it placed a space after it, which the BasicImage noticed to follow a CJK and thus removed the CJK.
This PR should fix it, and hopefully doesn't introduce regressions elsewhere.

AbstractScreen shouldn't pad CJK. BasicImage already did.

---

src/main/java/com/googlecode/lanterna/input/MouseCharacterPattern.java

Terminology's MOVE events have 0x1f as first parameter byte, so the
actionCode is 0 instead of 2.  This caused the MouseActionType to be
null and an NPE got thrown in ANSITerminal.filterMouseEvents.
Found during discussion of #277

add quirk for Terminal emulator "Terminology".

---

src/main/java/com/googlecode/lanterna/graphics/AbstractTheme.java
src/main/java/com/googlecode/lanterna/graphics/PropertiesTheme.java
src/main/java/com/googlecode/lanterna/graphics/PropertyTheme.java
src/main/java/com/googlecode/lanterna/graphics/SimpleTheme.java
src/main/java/com/googlecode/lanterna/gui2/AbstractBasePane.java
src/main/java/com/googlecode/lanterna/gui2/AbstractListBox.java
src/main/java/com/googlecode/lanterna/gui2/AbstractWindow.java
src/main/java/com/googlecode/lanterna/gui2/MultiWindowTextGUI.java
src/main/java/com/googlecode/lanterna/gui2/WindowShadowRenderer.java
src/main/java/com/googlecode/lanterna/terminal/swing/AWTTerminal.java
src/main/java/com/googlecode/lanterna/terminal/swing/AWTTerminalFrame.java
src/main/java/com/googlecode/lanterna/terminal/swing/GraphicalTerminalImplementation.java
src/main/java/com/googlecode/lanterna/terminal/swing/ScrollingAWTTerminal.java
src/main/java/com/googlecode/lanterna/terminal/swing/ScrollingSwingTerminal.java
src/main/java/com/googlecode/lanterna/terminal/swing/SwingTerminal.java
src/main/java/com/googlecode/lanterna/terminal/swing/SwingTerminalFrame.java
src/main/java/com/googlecode/lanterna/terminal/virtual/DefaultVirtualTerminal.java
src/test/java/com/googlecode/lanterna/graphics/PropertyThemeTest.java
src/test/java/com/googlecode/lanterna/gui2/LineWrappingLabelTest.java
src/test/java/com/googlecode/lanterna/gui2/MultiWindowManagerTest.java
src/test/java/com/googlecode/lanterna/issue/Issue216.java
src/test/java/com/googlecode/lanterna/screen/ScreenTriangleTest.java
src/test/java/com/googlecode/lanterna/screen/SimpleScreenTest.java
src/test/java/com/googlecode/lanterna/terminal/SimpleTerminalTest.java
src/test/java/com/googlecode/lanterna/terminal/TerminalTextGraphicsTest.java

- unused imports: removed
- unused field and local var: commented out
- raw usages of Class and Table: add `<?>` and `<String>` respectively
- stringToClass method promised more than it could handle (failed on generics): simplified to just return Object and let the calling code do the type casting.
- getRenderer() methods: hush up generics-warnings. (dynamic loading of instances just cannot ever be generics-clean)
- made AbstractBasePane generic to serve both BasePanes and Windows alike - required adding a self() method.
- PropertiesTheme is deprecated: port PropertiesThemeTest to PropertyThemeTest.
- warnings about serial id for Serializable classes: hushed up.
- warnings about missing enum cases in switches: add empty default label - we really don't want to handle all possible values in …

Fixwarnings

---

src/main/java/com/googlecode/lanterna/input/CtrlAltAndCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/CtrlAndCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/DefaultKeyDecodingProfile.java
src/main/java/com/googlecode/lanterna/input/KeyStroke.java
src/main/java/com/googlecode/lanterna/terminal/ansi/StreamBasedTerminal.java
src/test/java/com/googlecode/lanterna/terminal/TerminalInputTest.java

The number of Terminal programs that default to ^H for Backspace is still "too damn high" to ignore it.
The downside of accepting Ctrl-H as a second Backspace is, that applications cannot treat Ctrl-H differently from ^?, but then again, they probably shouldn't, anyway.
the second commit deals with Esc-prefixed ^H and ^?.  Previously, Esc ^H would fall back to a single character with ctrl+alt, while Esc ^? would have been two separate key strokes Esc and Backspace.
@mabe02, it's your decision...

Ctrl h backspace

---

src/main/java/com/googlecode/lanterna/gui2/LinearLayout.java

This fixes a small bug in LinearLayout: if the container is empty, it creates a TerminalSize with -1, which crashes.

Fix bug on LinearLayout with empty containers

---

src/main/java/com/googlecode/lanterna/gui2/MultiWindowTextGUI.java

Currently the `WindowTextGUI` only draws visible windows (since #201). Unfortunately this introduced a bug which caused lanterna redrawing until all windows are visible. This PR checks whether a window is invalid **and** visible, which should prevent this from happening.

Only check visible windows for invalidness

---

src/main/java/com/googlecode/lanterna/bundle/BundleLocator.java
src/main/java/com/googlecode/lanterna/gui2/TextBox.java

- when working with a local copy of lanterna things were breaking because the BundleLocator wasn't searching for the resources in src/main/resources like [LanternaThemes is](https://github.com/mabe02/lanterna/blob/master/src/main/java/com/googlecode/lanterna/bundle/LanternaThemes.java#L112).
- The logic for deciding whether to draw a vertical scrollbar in the edge case that the text is exactly the same height as the view area but a horizontal scrollbar has been drawn seemed pretty broken, so I fixed it, I think?

Two small fixes

---

docs/using-terminal.md

DefaultTerminalFactory is in com.googlecode.lanterna.terminal (https://github.com/mabe02/lanterna/blob/master/src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java#L19).

fix package name in documentation

---

src/main/java/com/googlecode/lanterna/terminal/ansi/TelnetTerminal.java
src/test/java/com/googlecode/lanterna/terminal/TelnetTerminalTest.java

I took a stab at fixing #332 ("readInput on Terminal from TelnetTerminalServer returns immediate EOF"). This also adds a demonstration of blocking input to TelnetTerminalTest.
Thanks for locating the code that needed to change, @avl42!
Please review carefully, as there is lots that I don't understand about the TELNET protocol and the Lanterna codebase.

Make read() block in TelnetTerminal

---

src/main/java/com/googlecode/lanterna/gui2/ComboBox.java

getSelectedItem should not throw IndexOutOfBoundsException if there is no selection
(selectedIndex is -1 for no selection)

getSelectedItem should not throw IndexOutOfBoundsException

---

src/main/java/com/googlecode/lanterna/gui2/Window.java
src/main/java/com/googlecode/lanterna/gui2/dialogs/MessageDialogBuilder.java
src/test/java/com/googlecode/lanterna/gui2/WelcomeSplashTest.java

This fixes an exception thrown for trying to supply Window.HINTs to the MessageDialogBuilder.
Also, change MessageDialogBuilder.setExtraWindowHints to accept any Collection<Window.HINT>, as there is really no need to confine to a Set.

Fix and Test for Issue #353

---

src/main/java/com/googlecode/lanterna/gui2/AbstractComponent.java
src/test/java/com/googlecode/lanterna/issue/Issue359.java

This fixes #359.
It also attempts to detect certain bugs early, where a component's onRemoved() is called from a wrong parent.
I am pretty sure that any such situation is a bug, but it is possible that such a bug went undetected so far, but will then disrupt a program. The change in onAdded() is the actual fix, that in onRemoved() is strictly optional.
(now rebased to release/3.0)

fix issue #359

---

src/main/java/com/googlecode/lanterna/gui2/dialogs/ActionListDialog.java

This is @asoltysik's PR #339 rebased to release/3.0
> Issue #338
> The condition to require a non-empty action list seemed rather arbitrary to me, so I'll leave this PR for your consideration.

allow empty action list in ActionListDialog

---

src/main/java/com/googlecode/lanterna/gui2/Window.java
src/main/java/com/googlecode/lanterna/gui2/dialogs/MessageDialogBuilder.java
src/test/java/com/googlecode/lanterna/gui2/WelcomeSplashTest.java

This fixes an exception thrown for trying to supply Window.HINTs to the MessageDialogBuilder.
Also, change MessageDialogBuilder.setExtraWindowHints to accept any
Collection<Window.HINT>, as there is really no need to confine to a Set.
Give Window.Hint a decent .toString() for debugging.
This fix is already merged to master, but might be good for release/3.0, too.

Fix and Test for Issue #353 rebased to release/3.0

---

src/main/java/com/googlecode/lanterna/gui2/AbstractComposite.java
src/test/java/com/googlecode/lanterna/issue/Issue374.java

- composite should only offer its component for focus if given component is enabled
- a disabled component in a border breaks forcus traversal
fixes #374

Fix AbstractComposite.nextFocus for disabled components

---

docs/using-terminal.md

Minor typo made the code example non-copy-pasteable.

Typo in using-terminal.md

---

src/main/java/com/googlecode/lanterna/terminal/swing/SwingTerminalFrame.java

To set a frame to borderless mode, one must dispose, then undecorate, and finally repack the frame. However, disposing a  SwingTerminalFrame will set its disposed flag to true, which will cause its pollInput() method to permanently send EOF KeyStrokes. This would not be a problem, but when repacking the frame, the flag is not set to false. The end result is a frame that will not return keyboard input.
My change sets the dispose flag to false when pack() is called so that one can dispose and repack the SwingTerminalFrame an arbitrary number of times.

Overwrote Window.pack() to set disposed variable to false in SwingTerminalFrame.

---

pom.xml
src/main/java/com/googlecode/lanterna/TextColor.java
src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java
src/main/java9/module-info.java

The PR has two commits and I recommend reviewing them individually:
- Packaging changes to create a multi-release jar file that works on Java 6+ and is a proper JPMS module (Java 9+). This bumps the minimum javac version to 9 but the resulting jar should work on Java 6 (untested).
- Remove the runtime dependency on the `java.desktop` module. This allows producing smaller runtime images if you don't need the terminal emulator parts nor the `TextColor.getColor()` method.
I tested it on Java 11 with a modularized version of the `OutputString` example both with and without the `java.desktop` module.
Is the package `com.googlecode.lanterna.bundle` meant to be used directly by the application/other libraries? If not, then its `exports` should be dropped.

Modularize for JPMS

---

src/main/java/com/googlecode/lanterna/input/EscapeSequenceCharacterPattern.java
src/main/java/com/googlecode/lanterna/input/KeyStroke.java
src/main/java/com/googlecode/lanterna/input/ScreenInfoCharacterPattern.java

F3-key typically sends `^[OR` if unmodified, or `^[[1;<n>R` with `<n>` between 2 and 8, if shift'ed, ctrl'ed or alt'ed. A CursorLocation on the other hand always looks like `^[[<row>;<col>R`.
Therefore, shift'ed, alt'ed or ctrl'ed F3 can not be safely distinguished from a CursorLocation, but a bare F3 usually can.
This patch will make sure that a bare F3 key cannot get mistakenly taken for a CursorLocation.

Workaround for possible F3 vs CursorLocation ambiguity.

---

src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java
src/main/java/com/googlecode/lanterna/terminal/TerminalFactory.java

Resolves #440
I was able to workaround this without needing to do any module splitting. The issue is that the runtime checks in `TerminalFactory.createTerminal` isn't enough to tell Graal that AWT/Swing isn't going to be needed. I created a `createHeadlessTerminal` method which can be verified AOT that the emulators aren't going to be used. Using `createHeadlessTerminal` I'm able to use lanterna + native-image without any issues.
I'm not sure how you feel about this solution. It's simple, but maybe adding a new method to TerminalFactory isn't ideal? But I don't see many other alternatives.

DefaultTerminalFactory Graal native-image support

---

src/main/java/com/googlecode/lanterna/gui2/AbstractBasePane.java
src/main/java/com/googlecode/lanterna/gui2/AbstractComponent.java
src/main/java/com/googlecode/lanterna/gui2/AbstractComposite.java
src/main/java/com/googlecode/lanterna/gui2/AbstractListBox.java
src/main/java/com/googlecode/lanterna/gui2/ActionListBox.java
src/main/java/com/googlecode/lanterna/gui2/Button.java
src/main/java/com/googlecode/lanterna/gui2/CheckBox.java
src/main/java/com/googlecode/lanterna/gui2/ComboBox.java
src/main/java/com/googlecode/lanterna/gui2/Component.java
src/main/java/com/googlecode/lanterna/gui2/RadioBoxList.java
src/main/java/com/googlecode/lanterna/gui2/TextBox.java
src/main/java/com/googlecode/lanterna/gui2/menu/Menu.java
src/main/java/com/googlecode/lanterna/gui2/menu/MenuBar.java
src/main/java/com/googlecode/lanterna/gui2/menu/MenuItem.java
src/main/java/com/googlecode/lanterna/gui2/table/Table.java
src/test/java/com/googlecode/lanterna/issue/Issue452.java
src/test/java/com/googlecode/lanterna/issue/Issue452Test.java

Mouse support for: Button, TextBox, CheckBox, ActionListBox, RadioListBox, Menu and Table and a bit of refactoring. 
I mostly edited handleKeyStroke methods of these components but when I came across MenuBar, Menu and MenuItem  I ran into a problem with how components were drawn if there was or was not Menu at the top. What I found out was that if there is a Menu bar, all components would be down by 1 row but their coordinates would stay the same, as if there was no Menu bar and that was messing up mouse clicks, obviously. So what I have done is: edited AbstactComposite#setComponent to take into account that +1 if there is MenuBar present and since EmptyMenuBar is an inner class I had to do a bit of an ugliness. With that I also removed what I believe was another hack in AbstractBasePane …

Mouse support, Issue #452

---

src/main/java/com/googlecode/lanterna/terminal/ansi/TelnetTerminal.java

I apologize that this even happened in the first place... pah!  It's eclipse's fault, for apparently working despite the bug  ;-) 
Explanation:
When a timeout is set on a Socket, then by documentation the read(...) call throws an exception if it doesn't receive data in time.
eclipse instead just silently returned 0 bytes without throwing an exception, thus I forgot to add the necessary try-catch block.
For now I cannot try this change with eclipse, so I do hope that eclipse at least won't complain about the catch...

Fix for Issue #537

---

src/main/java/com/googlecode/lanterna/terminal/swing/GraphicalTerminalImplementation.java

In the Swing Terminal Emulator, a blinking cursor currently cannot be made invisible with setCursorVisible(false) - it's still there and blinking.
/**
* Steps to reproduce the blinking cursor bug
*/
public static void main(String[] args) throws Exception {
TerminalEmulatorDeviceConfiguration deviceConfiguration =
TerminalEmulatorDeviceConfiguration.getDefault()
.withBlinkLengthInMilliSeconds(333)
.withCursorStyle(TerminalEmulatorDeviceConfiguration.CursorStyle.UNDER_BAR)
.withCursorBlinking(true);
DefaultTerminalFactory factory = new DefaultTerminalFactory();
factory.setTerminalEmulatorDeviceConfiguration(deviceConfiguration);
factory.setInitialTerminalSize(new TerminalSize(80, 25));
Terminal terminal = factory.createTerminal(); // creates a Swing terminal
terminal.enterPrivateMode(); …

Do not display blinking cursor when setCursorVisible(false) called

---

project/build.properties
src/main/java/com/googlecode/lanterna/gui2/AbstractBasePane.java

Hi,
When using this library, I noticed that when overriding `afterLeaveFocus(direction: Interactable.FocusChangeDirection, nextInFocus: Interactable)`, the `nextInFocus` variable was actually set to the current Interactable and not the target one.
This patch fixes that.
Thank you

Fix: pass correct target focus to previous focus

---

src/main/java/com/googlecode/lanterna/gui2/SplitPanel.java

Currently, the thumb in `SplitPanel` gets focus on Tab, but itself doesn't handle Tab key again to pass the focus forward. Same for reverse Tab. This effectively breaks the whole tabbing idea if any `SplitPanel` is present in the window.
To fix this, this change disables the thumb component.

Disable thumb in SplitPanel

---

jitpack.yml

Hi,
This small configuration file makes it such that Jitpack is able to compile the project, making snapshots easily available.
Currently it fails because javac from JDK 8 encounters an unrecognised argument:
https://jitpack.io/com/github/mabe02/lanterna/54f5b4ca6b/build.log
This is fixed when using JDK 9:
https://jitpack.io/com/github/freyacodes/lanterna/2e63dd24b2/build.log

Fix Jitpack compilation

---

src/test/java/com/googlecode/lanterna/issue/Issue595.java

The fix for #595 as proposed by #596 looks good to me.
The test proposed in #596 would hang with the `AnimatedLabel` Thread.
This PR proposes a modification so that now matter if `Issue595` test fails or succeeds:
- it never hangs
- indicates test failure via:
- output to stderr
- returned exit code

Prevent Test From Hanging With AnimatedLabel Thread

---

src/main/java/com/googlecode/lanterna/bundle/BundleLocator.java

Custom control implementations are not supported in named modules. From java 9 on the default property resource bundles will use utf-8 as default charset. So we can just load the resources without the control if it fails.
Fixes #620

Issue-620: Load ResourceBundle with default Control if custom Control fails

---

pom.xml
src/main/java/com/googlecode/lanterna/graphics/AbstractTextGraphics.java
src/main/java/com/googlecode/lanterna/graphics/DoublePrintingTextGraphics.java
src/main/java/com/googlecode/lanterna/graphics/NullTextGraphics.java
src/main/java/com/googlecode/lanterna/graphics/SubTextGraphics.java
src/main/java/com/googlecode/lanterna/graphics/TextGraphics.java
src/main/java/com/googlecode/lanterna/graphics/TextGraphicsWriter.java
src/main/java/com/googlecode/lanterna/gui2/DefaultTextGUIGraphics.java
src/main/java/com/googlecode/lanterna/screen/ScreenTranslator.java
src/main/java/com/googlecode/lanterna/terminal/ansi/StreamBasedTerminal.java
src/test/java/com/googlecode/lanterna/screen/ScreenTextGraphicsTest.java

This PR **enhances** `TextGraphics` and `TextGraphicsWriter` (and its subclasses) in that they can translate their relative `TerminalPosition`s to the absolute `TerminalPosition`s used by the `Screen` object. 
This is useful e.g. for computing the current cursor position in an interactive application that writes to TextGraphics an user prompt and then need to position terminal cursor. Or for many other purposes.
I've added also tests to check this new behaviour.
During test development, I've realized there's a significant delay between test setup and the actual test, caused by 5s terminal wait on size query. I added a possibility to configure this delay using system properties; the system property is then used in Maven surefire configuration for test run.

ENH: Support to-screen coordinates translation

---

docs/using-terminal.md

The existing link does several redirects and ends up on an Azure web server which appears to be hosting tech support scam material.  (I've reported it to Microsoft.)
This is the only citebite reference in the Lanterna docs.
Fixes #640

Change malicious link to a link to an Oracle Java doc page.
