- src/main/java/com/googlecode/lanterna/gui2/InteractableLookupMap.java
> make robust against ZERO size. (Issue#134)

- src/main/java/com/googlecode/lanterna/gui2/SeparateTextGUIThread.java
- src/main/java/com/googlecode/lanterna/terminal/ansi/UnixLikeTerminal.java
1st commit: attempt at fixing #154  
2nd commit: attempt at fixing #158
> execute-stty-with-redirect-for-Java6 & SeparateTextGUIThread public

- src/main/java/com/googlecode/lanterna/screen/TerminalScreen.java
- src/main/java/com/googlecode/lanterna/terminal/ansi/ANSITerminal.java
As it was, automatic refresh mode would have spoilt scroll optimization...
I think after-all this approach is even better than my changing default to DELTA.
PS: follow-up to #151 and #138
> Three fixes around scrolling

- src/main/java/com/googlecode/lanterna/gui2/AbstractBorder.java
> Let Border pass through LayoutData

- src/examples/java/com/googlecode/lanterna/examples/DrawRectangle.java
- src/examples/java/com/googlecode/lanterna/examples/OutputChar.java
- src/examples/java/com/googlecode/lanterna/examples/OutputString.java
Hi,
Maybe these examples can be helpful to others. Feel free to reorganize/edit/etc or throw away them.
Thank you for your great library.
Péter Borkuti
> Simple examples

- src/test/java/com/googlecode/lanterna/gui2/ComboBoxTest.java
- src/test/java/com/googlecode/lanterna/gui2/ListBoxTest.java
This is a redo of ben dale's #186 with the only change, that it contains just a single commit of those two files, and avoids the merge-commit, leaving the resulting version tree just a tiny bit leaner.
Not sure if that was even worth it, but well...  now mabe02 has the choice :-)
> Restore tests to former glory (ben-dale)

- src/main/java/com/googlecode/lanterna/input/EscapeSequenceCharacterPattern.java
This will fix ctrl-cursor keys for putty, as long as we don't accidentally stumble into terminfo's "keypad_xmit" mode.
> Add quirk to support Putty ctrl-cursor-key combo.

- src/main/java/com/googlecode/lanterna/gui2/table/DefaultTableRenderer.java
> Fix DefaultTableRenderer when rendering empty tables or changing table model

- src/main/java/com/googlecode/lanterna/TerminalTextUtils.java
- src/main/java/com/googlecode/lanterna/graphics/AbstractTextGraphics.java
Implements underline. See also issue #239.
Should have minimal performance impact outside of text which uses escape sequences.
> Framework for handling ANSI escape sequences for selective styling of running text

- src/main/resources/multilang/lanterna-ui_zh-CN.properties
- src/main/resources/multilang/lanterna-ui_zh-TW.properties
> chinese localization added

- src/main/java/com/googlecode/lanterna/gui2/WindowShadowRenderer.java
- src/test/java/com/googlecode/lanterna/issue/Issue249.java
Issue #249 demo & fix - thanks to celyo for reporting
> Issue #249 demo & fix

- src/main/java/com/googlecode/lanterna/gui2/GridLayout.java
- src/main/java/com/googlecode/lanterna/gui2/LinearLayout.java
Thanks to @kwantumWare for pointing it out in Issue #256 
The problem leading to Issue #256 might actually have been a different one, but it helped spotting this little inconsistency among the three LayoutManagers.
> LinearLayout now behaving like other Layouts with bad LayoutData.

- pom.xml
junit dependency should have `test` scope.
> Fix junit dependency scope

- src/main/java/com/googlecode/lanterna/gui2/AbstractBasePane.java
- src/main/java/com/googlecode/lanterna/gui2/InteractableLookupMap.java
- src/test/java/com/googlecode/lanterna/issue/Issue274.java
> Mouseevent to Interactable mapping was flaky

- src/main/java/com/googlecode/lanterna/TerminalTextUtils.java
- src/main/java/com/googlecode/lanterna/graphics/AbstractTextGraphics.java
- src/main/java/com/googlecode/lanterna/graphics/NullTextGraphics.java
- src/main/java/com/googlecode/lanterna/graphics/StyleSet.java
- src/main/java/com/googlecode/lanterna/graphics/TextGraphics.java
- src/main/java/com/googlecode/lanterna/gui2/TextGUIGraphics.java
- src/main/java/com/googlecode/lanterna/screen/AbstractScreen.java
This is in preparation for a new approach to rich text handling.
(it also includes the previous bugfix in AbstractScreen)
> Refactoring "StyleSet"

- src/main/java/com/googlecode/lanterna/TerminalTextUtils.java
- src/main/java/com/googlecode/lanterna/graphics/AbstractTextGraphics.java
- src/main/java/com/googlecode/lanterna/graphics/NullTextGraphics.java
- src/main/java/com/googlecode/lanterna/graphics/StyleSet.java
- src/main/java/com/googlecode/lanterna/graphics/TextGraphics.java
- src/main/java/com/googlecode/lanterna/graphics/TextGraphicsWriter.java
- src/main/java/com/googlecode/lanterna/gui2/TextGUIGraphics.java
- src/main/java/com/googlecode/lanterna/screen/AbstractScreen.java
- src/main/java/com/googlecode/lanterna/screen/WrapBehaviour.java
- src/test/java/com/googlecode/lanterna/screen/TextGraphicsWriterTest.java
This is the new TextGraphicsWriter sitting on top of TextGraphics and rendering flowing rich text even with word wrapping.  The Test is a modified copy of the CJK-test to show off what it can do.
evaluate it, and if you like it, please add comments... (I'll be mostly offline for the rest of the week and didn't want it resting on my hard disk.)
If you pull this, it already contains the other two recent PRs.
> Text graphics writer

- src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java
- src/main/java/com/googlecode/lanterna/terminal/ansi/ANSITerminal.java
- src/main/java/com/googlecode/lanterna/terminal/ansi/StreamBasedTerminal.java
- src/test/java/com/googlecode/lanterna/TestTerminalFactory.java
- src/test/java/com/googlecode/lanterna/gui2/FullScreenTextGUITest.java
- src/test/java/com/googlecode/lanterna/issue/Issue274.java
- src/test/java/com/googlecode/lanterna/screen/MultiScreenTest.java
- src/test/java/com/googlecode/lanterna/terminal/PrivateModeTest.java
- src/test/java/com/googlecode/lanterna/terminal/TerminalInputTest.java
cumulative PR - see the single commits
> Terminal factory

- src/test/java/com/googlecode/lanterna/issue/Issue274.java
- src/test/java/com/googlecode/lanterna/terminal/PrivateModeTest.java
> another two obsolete imports

- src/main/java/com/googlecode/lanterna/terminal/ansi/UnixLikeTerminal.java
> Ctrl-C: only exitPrivateMode() if in private mode.

- docs/using-terminal.md
thx a lot for lanterna, great stuff :)
> update method name

- src/main/java/com/googlecode/lanterna/gui2/MultiWindowTextGUI.java
This commit only affects instances of `MultiWindowTextGUI`.
In the case that the background pane has interactable components, it may be desirable to allow focus to pass to the background pane. This is currently fully supported so long as no windows are opened, but as soon as a window is opened it is no longer possible to return focus to the background pane.
`setActiveWindow(null)` now allows the background pane to have focus, and if no suitable window can be found to replace a removed active window, then focus returns to the background pane.
> Allow focus to pass back to background pane

- src/main/java/com/googlecode/lanterna/graphics/BasicTextImage.java
just "converted" @adam-arold's fix-suggestion in issue #322 to a PR.
> Fix as suggested in issue #322

- src/main/java/com/googlecode/lanterna/terminal/swing/TerminalEmulatorDeviceConfiguration.java
- add withBlinkLengthInMilliSeconds
- change withLineBufferScrollbackSize: do not copy the TerminalEmulatorDeviceConfiguration, set the private fiels
- add withCursorStyle
- add withCursorColor
- add withCursorBlinking
- add withClipboardAvailable
> Can not alter TerminalEmulatorDeviceConfiguration #327

- src/main/java/com/googlecode/lanterna/graphics/BasicTextImage.java
- src/test/java/com/googlecode/lanterna/issue/Issue385.java
This PR fixes issue #385 and adds Andrey's testcase.  Thanks, Andrey, for reporting it!
> Fix Issue #385

- src/main/java/com/googlecode/lanterna/gui2/table/Table.java
- src/test/java/com/googlecode/lanterna/issue/Issue387.java
Hi,
This is a proposed PR for #387 issue. What do you think?
Regards,
Martin
> Table component - add support for PgUp and PgDn

- src/main/java/com/googlecode/lanterna/terminal/swing/GraphicalTerminalImplementation.java
> suppress shift for ReverseTab.

- src/main/java/com/googlecode/lanterna/terminal/ansi/TelnetTerminal.java
- src/test/java/com/googlecode/lanterna/gui2/GUIOverTelnet.java
This is a simpler alternative for PR #428 .  I also added the GuiOverTelnet part from that PR, so it would be a full drop-in replacement.
> Issue #417: Detect client abruptly closing the socket - alternative smaller patch

- src/main/java/com/googlecode/lanterna/screen/TerminalScreen.java
@mabe02: Only merge, if @bleehome approves it...
> Maybe fix for Issue #431

- docs/tutorial/Tutorial03.md
Was just going through the examples when I found these two lines stuck together, wherein the previous tutorials, it's in two lines.
> Fixing format by adding new line where needed

- src/main/java/com/googlecode/lanterna/terminal/swing/AWTTerminal.java
- src/main/java/com/googlecode/lanterna/terminal/swing/SwingTerminal.java
- src/main/java/com/googlecode/lanterna/terminal/swing/TerminalInputMethodRequests.java
Resolves #439
I positioned the composition box right below the cursor like so:
> Add IME support to terminal emulators

- src/main/java/com/googlecode/lanterna/gui2/table/Table.java
- src/main/java/com/googlecode/lanterna/gui2/table/TableModel.java
- src/main/java/com/googlecode/lanterna/terminal/virtual/DefaultVirtualTerminal.java
- src/main/java/com/googlecode/lanterna/terminal/virtual/TextBuffer.java
- src/test/java/com/googlecode/lanterna/gui2/TableUnitTests.java
> Ensure Table.selectedRow integrity, and update automatically

- src/main/java/com/googlecode/lanterna/gui2/AsynchronousTextGUIThread.java
- src/main/java/com/googlecode/lanterna/gui2/SeparateTextGUIThread.java
> Add AsynchronousTextGUIThread.waitForStop with timeout

- src/main/java/com/googlecode/lanterna/gui2/table/DefaultTableRenderer.java
- src/main/java/com/googlecode/lanterna/gui2/table/TableRenderer.java
- src/test/java/com/googlecode/lanterna/gui2/TableUnitTests.java
> Add option to hide scrollbars in Table renderer

- src/main/java/com/googlecode/lanterna/gui2/table/DefaultTableRenderer.java
- src/main/java/com/googlecode/lanterna/gui2/table/TableRenderer.java
- src/test/java/com/googlecode/lanterna/gui2/TableUnitTests.java
> Add option to render table columns all the way to right edge

- src/main/java/com/googlecode/lanterna/TextColor.java
- src/main/java/com/googlecode/lanterna/terminal/swing/TerminalEmulatorPalette.java
- src/test/java/com/googlecode/lanterna/terminal/SGRTest.java
- src/test/java/com/googlecode/lanterna/terminal/Terminal4bitColorTest.java
> Add bright (4-bit) colors to TextColor.ANSI

- src/main/java/com/googlecode/lanterna/gui2/Panel.java
When using Lanterna I noticed a quite high CPU usage whenever I had some Components invisible. After some debugging I could find the problem in the Panel isInvalid() method.
This checks if one of its children components is invalid. If this is the case, all components are redrawn, skipping the invisible ones. This way the invisible components will not be drawn and will not be set to valid again. In the next isInvalid check, the invisible components cause the Panel to be redrawn again.
Ignore invisible components during `Panel.isInvalid()` check.
```java
@Override
public boolean isInvalid() {
synchronized(components) {
for(Component component: components) {
// a Panel (Container) isInvalid when any child component isInvalid AND also isVisible
if(component.isInvalid() && …
```
> Avoid unnecessary draw calls for invisible components in a Panel (Container)

- docs/examples/gui/tables.md
> Update tables.md fixed typo

- src/main/java/com/googlecode/lanterna/gui2/MultiWindowTextGUI.java
Not sure if this meets style guidelines, but it seems to me like a minimal fix for #559 .
> Fix for Issue #559

- src/main/java/com/googlecode/lanterna/gui2/RadioBoxList.java
customizable item text instead of toString
> introduced RadioBoxListItemRenderer.getItemText

- docs/GUIGuideWindows.md
I'm guessing lanterna 3 changed this API a bit, but...yeah, those static bevel methods don't accept a component as a parameter anymore.
> Update GUIGuideWindows.md to use withBorder

- README.md
Clearly Lanterna is not intended for performing any kind of frame rate sensitive animation. I went ahead and did it anyways.
I present for your consideration [ScaLaMatrixRain](https://github.com/gabrieljones/ScaLaMatrixRain).
> README.md: Projects: ScaLaMatrixRain

- src/main/java/com/googlecode/lanterna/input/MouseAction.java
- src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java
- src/main/java/com/googlecode/lanterna/terminal/MouseCaptureMode.java
- src/main/java/com/googlecode/lanterna/terminal/swing/AWTTerminal.java
- src/main/java/com/googlecode/lanterna/terminal/swing/AWTTerminalImplementation.java
- src/main/java/com/googlecode/lanterna/terminal/swing/GraphicalTerminalImplementation.java
- src/main/java/com/googlecode/lanterna/terminal/swing/SwingTerminal.java
- src/main/java/com/googlecode/lanterna/terminal/swing/SwingTerminalImplementation.java
This would add mouse support for AWT and Swing terminals
> Mouse support for AWT/Swing terminals
